name: CI Pipeline

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 45
    strategy:
      matrix:
        service: 
          - bank-my-library
          - calculator_microservice
          - deal_microservice
          - dossier_microservice
          - statement_microservice
          - API_Gateway_microservice

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: maven-${{ runner.os }}-${{ matrix.service }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-${{ runner.os }}-${{ matrix.service }}-

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build and Test
        run: |
          cd ${{ matrix.service }}
          mvn clean verify

      - name: Verify Jacoco Report
        run: |
          echo "Checking report in ${{ matrix.service }}"
          ls -la ${{ matrix.service }}/target/site/jacoco/jacoco.xml
          test -f ${{ matrix.service }}/target/site/jacoco/jacoco.xml || exit 1

      - name: CodeCov Upload
        timeout-minutes: 5
        uses: codecov/codecov-action@v4  
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ${{ matrix.service }}/target/site/jacoco/jacoco.xml
          flags: ${{ matrix.service }}
          verbose: true  
          fail_ci_if_error: false

      - name: SonarCloud Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd ${{ matrix.service }}
          mvn sonar:sonar \
            -Dsonar.projectKey=air2x_credit_bank \
            -Dsonar.organization=air2x \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=$SONAR_TOKEN
