name: CI Pipeline

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [calculator_microservice, deal_microservice, dossier_microservice, statement_microservice, API_Gateway_microservice]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: |
          cd ${{ matrix.service }}
          mvn clean install -DskipTests

      - name: Run tests and calculate coverage
        run: |
          cd ${{ matrix.service }}
          mvn test jacoco:report

      - name: Upload coverage to CodeCov
        run: bash <(curl -s https://codecov.io/bash) -f ${{ matrix.service }}/target/site/jacoco/jacoco.csv

      - name: SonarCloud Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          cd ${{ matrix.service }}
          mvn sonar-scanner \
            -Dsonar.projectKey=air2x \
            -Dsonar.organization=air2x \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=$SONAR_TOKEN
